* INICIADO PELO EXECUTAVEL
IF _vfp.StartMode <> 0
	ON SHUTDOWN DO ENCERRAR
ELSE
	ON SHUTDOWN
ENDIF

_SCREEN.Visible		= .T.
_SCREEN.WindowState	= 2

DO AMBIENTAR

DO FORM EMAIL_EDITAR

READ EVENTS
CLEAR ALL

RETURN

PROC AMBIENTAR
**************
	SET TALK OFF
	SET ESCAPE OFF
	SET EXCL OFF
	SET DELE ON
	SET DATE BRITISH
	SET CURSOR ON
	SET NOTIFY OFF
	SET SAFETY OFF
	SET READBORDER ON
	SET DECIMAL TO 8
	SET REPROCESS TO 3 SECONDS
	SET POINT TO ','
	SET SEPA TO '.'
	SET EXACT OFF
	SET NEAR OFF
	SET CONFIRM ON
	SET CLOCK STATUS
	SET CENTURY ON
	SET MEMOWIDTH TO 512
	SET HOURS TO 24
	SET ENGINEBEHAVIOR 80
	SET REPORTBEHAVIOR 90
	SET PATH TO 
RETURN

PROC ENCERRAR
	ON SHUTDOWN
	CLOSE DATA
	SET PROCEDURE TO
	CLEAR EVENTS

	CLEAR WINDOWS
	SET PATH TO
	CANCEL
ENDPROC

PROC CENTRALIZAR
****************
LPARAMETERS toFORM 
	IF VARTYPE(toFORM) <> 'O'
		RETURN(.F.)
	ENDIF
	
	_SCREEN.WindowState = 2
	toFORM.Top		= ( _SCREEN.Height / 2 ) - ( toFORM.Height / 2 )
	toFORM.Left		= ( _SCREEN.Width / 2 ) - ( toFORM.Width / 2 )
RETURN

